// <auto-generated/>
#pragma warning disable 1591
namespace XanaduProject.Factories.ShaderFactoryHelpers
{
    public static class FragmentShaderUniforms
    {
        public const string TILES_GRID_SIZE = "tiles_grid_size";
        public const string TILES_WAVE_SPEED = "tiles_wave_speed";
        public const string TILES_WAVE_FREQUENCY = "tiles_wave_frequency";
        public const string TILES_MIN_OPACITY = "tiles_min_opacity";
        public const string TILES_MAX_OPACITY = "tiles_max_opacity";
    }
}
